name: Refresh Threads Tokens

on:
  schedule:
        # Se ejecuta todos los días a las 00:00 AM UTC
    # - cron: '0 0 * * *'
  workflow_dispatch: # Permite la ejecución manual desde la UI de GitHub

jobs:
  refresh-tokens:
    runs-on: ubuntu-latest
    steps:
      - name: Call refresh tokens endpoint
        run: |
          curl -X POST \
            -H "x-cron-secret: ${{ secrets.CRON_SECRET }}" \
            "${{ secrets.PRODUCTION_URL }}/api/threads/refresh-tokens"